version: '3'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
  product-service:
    build: ./product-service
    ports:
      - "8083:8083"

  load-balancer:
    image: "dockercloud/haproxy"
    links:
      - api-gateway
      - auth-service
      - product-service
      - order-service
    ports:
      - "80:80"
    environment:
      - BALANCE=roundrobin
