spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - RequestAuthFilter
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/order/**

        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/product/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
  application:
    name: api-gateway
  datasource:
    url: jdbc:h2:mem:ecommDb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /ecomm

auth:
  url: http://localhost:8081/auth/v1/api/user/info/

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  skiptranslation: /auth/v1/api/user
