spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/order/**

        - id: product-service
          uri: http://product-service:8083
          predicates:
            - Path=/product/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - RequestAuthFilter
  application:
    name: api-gateway
  datasource:
    url: jdbc:h2:mem:ecommDb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /ecomm

auth:
  url: http://auth-service:8081/auth/v1/api/user/info/

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  skiptranslation: /auth/v1/api/user,/auth/h2-console,/order/h2-console,/product/h2-console,/auth/v3/api-docs,/order/v3/api-docs,/product/v3/api-docs,/auth/swagger-ui,/order/swagger-ui,/product/swagger-ui
