name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker to Google Container Registry
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build and Push Docker Images
        run: |
          docker-compose build
          docker-compose push

  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy API Gateway to Cloud Run
        run: |
          gcloud run deploy api-gateway --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-gateway:latest  --platform managed --allow-unauthenticated 
          gcloud run deploy api-gateway --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-gateway:latest  --platform managed --allow-unauthenticated 

      - name: Deploy Auth Service to Cloud Run
        run: |
          gcloud run deploy auth-service --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/auth-service:latest  --platform managed --allow-unauthenticated 
          gcloud run deploy auth-service --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/auth-service:latest  --platform managed --allow-unauthenticated 

      - name: Deploy Order Service to Cloud Run
        run: |
          gcloud run deploy order-service --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/order-service:latest  --platform managed --allow-unauthenticated 
          gcloud run deploy order-service --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/order-service:latest  --platform managed --allow-unauthenticated 

      - name: Deploy Product Service to Cloud Run
        run: |
          gcloud run deploy product-service --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/product-service:latest  --platform managed --allow-unauthenticated 
          gcloud run deploy product-service --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/product-service:latest  --platform managed --allow-unauthenticated 
